blog/urls.py
from django.urls import path
from blog.views import *

from blog.rss import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_home_view, name='blog_home_view'),
    path('<int:pid>', blog_single_view, name='blog_single_view'),
    path('categor/<str:cat_name>', blog_home_view, name='category'),
    path('tag/<str:tag_name>', blog_home_view, name='tag'),
    path('author/<str:author_name>', blog_home_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', LatestEntriesFeed()),
    path('test', test, name='test')   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'
urlpatterns = [
    path('', home_page, name='home_view'),
    path('contact', contact_page, name='contact_view'),
    path('about', about_page, name='about_view'),
    path('news-letter', news_letter_page, name='news_letter')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=255)   
    def __str__(self):
        return self.name
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    views = models.IntegerField(default=0)
    tags = TaggableManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # or (on_delete=models.SET_NULL)
    category = models.ManyToManyField(Category)
    status = models.BooleanField(default=False)
    need_to_login = models.BooleanField(default=False)
    image = models.ImageField(upload_to='blog/', default='blog/2switch.png')
    created_data = models.DateTimeField(auto_now_add=True)
    updated_data = models.DateTimeField(auto_now=True)
    published_data = models.DateTimeField(null=True)    
    class Meta:
        ordering = ['-published_data',]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:blog_single_view', kwargs={'pid': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created_date',)
    
    def __str__(self):
        return (f'{self.name} / {self.subject}')

blog/forms.py
from dataclasses import fields
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']
        

blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, HttpResponseRedirect
from blog.models import Post, Comment
from django.utils import timezone
from django.core.paginator import Paginator, InvalidPage
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse


def blog_home_view(request, **kwargs):    
    posts = Post.objects.filter(published_data__lte=timezone.now(), status=True)
    
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_name') != None:
        posts = posts.filter(author__username=kwargs['author_name'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
        
    posts = Paginator(posts, 3)
    page_number = request.GET.get('page')

    try:
        posts = posts.page(page_number)
    except (InvalidPage):
        posts = posts.page(1)
        
    context = {'posts': posts} 
    return render(request, 'blog/blog-home.html', context)


def blog_single_view(request, pid):
    single = get_object_or_404(Post, id=pid, status=True, published_data__lte=timezone.now())
    if single.need_to_login and not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    else:
        single.views +=1 
        single.save()
        
        form = CommentForm()
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                messages.add_message(request, messages.SUCCESS, 'Your comment has been submitted')
                form.save()
            else:
                messages.add_message(request, messages.ERROR, "Your comment has not been submitted")
                
        comments = Comment.objects.filter(post=pid, approved=True)
        context = {'single': single, 'comments': comments, 'form':form}
        
        try:
            next = get_list_or_404(Post, id__gt=single.id, published_data__lte=timezone.now(), status=True)
            context.update({'next':next[0]})
        except:
            pass    
        try:
            prev = get_list_or_404(Post, id__lt=single.id, published_data__lte=timezone.now(), status=True)
            context.update({'prev':prev[-1]})
        except:
            pass
            
        return render(request, 'blog/blog-single.html', context)


def blog_search(request):
    posts = Post.objects.filter(published_data__lte=timezone.now(), status=True)
    if request.method == 'GET':
        if request.GET.get('search'):
            search = request.GET.get('search')
            posts = posts.filter(content__contains=search)
    context = {'posts': posts} 
    return render(request, 'blog/blog-home.html', context)


def test(request):
    return render(request, 'test.html')

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_custome_tags %}

{% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
					
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg'  %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg'  %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %},{% endif %}</li>
							{% endfor %}
							<!---<li><a href="">{{post.category.all|join:", "}}</a></li>--->
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_name=post.author.username %}">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_data|date:'d-M-Y G:i'}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.views}} Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comment pid=post.id %} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src={{post.image.url}} alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:blog_single_view' pid=post.id %}">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
							<!---{{post.content|truncatewords:15}}--->
							{{post.content|truncatechars:50}}
						</p>
						<a href="#" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">
						{% if posts.has_previous %}
						<li class="page-item">
							<a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
						</li>
						{% endif %}

						{% for i in posts.paginator.page_range %}
							<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
						{% endfor %}

						{% if posts.has_next %}
						<li class="page-item">
							<a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-right"></span>
								</span>
							</a>
						</li>
						{% endif %}
					</ul>
				</nav>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% latest %}
					<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg'  %}" alt=""></a>
					</div>
					{% category %}
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
										</div>
									</div>
									<input type="text" class="form-control" id="inlineFormInputGroup"
										placeholder="Enter email" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter email'">
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latests Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center"> 
            <div class="thumb">
                <img class="img-fluid" src={{post.image.url}} alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_single_view' pid=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <!---<p>{{post.published_data|date:'d-m-y  G:i'}}</p>--->
                <p>{{post.published_data|naturaltime}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-category.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for cat, count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=cat %}" class="d-flex justify-content-between">
                <p>{{cat}}</p>
                <p>{{count}}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-single-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
	<h4 class="tagcloud-title"> Tag Clouds </h4>
		<ul>
			{% for tag in single.tags.all %}
				<li>
					<a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>
				</li> 
			{% endfor %}
		</ul>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_custome_tags %}
{% load humanize %}

{% block content %}
<div class="header-top">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
				<ul>
					<li><a href="#">Visit Us</a></li>
					<li><a href="#">Buy Tickets</a></li>
				</ul>
			</div>
			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
				<div class="header-social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container main-menu">
	<div class="row align-items-center justify-content-between d-flex">
		<div id="logo">
			<a href="index.html"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
		</div>
		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li class="menu-has-children"><a href="">Blog</a>
					<ul>
						<li><a href="blog-home.html">Blog Home</a></li>
						<li><a href="blog-single.html">Blog Single</a></li>
					</ul>
				</li>
				<li class="menu-has-children"><a href="">Pages</a>
					<ul>
						<li><a href="elements.html">Elements</a></li>
						<li class="menu-has-children"><a href="">Level 2 </a>
							<ul>
								<li><a href="#">Item One</a></li>
								<li><a href="#">Item Two</a></li>
							</ul>
						</li>
					</ul>
				</li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav><!-- #nav-menu-container -->
	</div>
</div>
</header><!-- #header -->

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{single.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:home_view' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:blog_home_view' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> <a href="{% url 'blog:blog_single_view' pid=single.id %}">
						{{single.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src={{single.image.url}} alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">

							{% for cat in single.category.all %}
							<a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last%},{% endif %}
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a
									href="{% url 'blog:author' author_name=single.author.username %}">{{single.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{single.published_data|date:'d-M-Y G:i'}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{single.views}} views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{single.title}}</h3>
						<p class="excert">
							{{single.content|safe}}
						</p>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							{% if prev %}
							<div class="thumb">
								<a href="{% url 'blog:blog_single_view' pid=prev.id %}"><img class="img-fluid"
										src={{prev.image.url}} alt=""></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:blog_single_view' pid=prev.id %}"><span
										class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Pervious post</p>
								<a href="{% url 'blog:blog_single_view' pid=prev.id %}">
									<h4>{{prev.title}}</h4>
								</a>
							</div>
							{% else %}
							<p></p>
							{% endif %}
						</div>
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							{% if next %}

							<div class="detials">
								<p>Next post</p>
								<a href="{% url 'blog:blog_single_view' pid=next.id %}">
									<h4>{{next.title}}</h4>
								</a>
							</div>

							<div class="arrow">
								<a href="{% url 'blog:blog_single_view' pid=next.id %}"><span
										class="lnr text-white lnr-arrow-right"></span></a>
							</div>

							<div class="thumb">
								<a href="{% url 'blog:blog_single_view' pid=next.id %}"><img class="img-fluid"
										src={{next.image.url}} alt=""></a>
							</div>

							{% else %}
							<p></p>
							{% endif %}
						</div>

					</div>
				</div>

				<!---<div class="comments-area">
					<div id="disqus_thread"></div>
					<script>
						/**
						*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
						*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
						/*
						var disqus_config = function () {
						this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
						this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
						};
						*/
						(function () { // DON'T EDIT BELOW THIS LINE
							var d = document, s = d.createElement('script');
							s.src = 'https://127-0-0-1-8000-rz77rmpixp.disqus.com/embed.js';
							s.setAttribute('data-timestamp', +new Date());
							(d.head || d.body).appendChild(s);
						})();
					</script>
					<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
							powered by Disqus.</a></noscript>
				</div>--->
				<div class="comments-area">
					<h4>{{comments|length}} Comments</h4>
					{% for comment in comments %}
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{comment.name}}</a></h5>
									<p class="date">{{comment.created_date|naturalday}}</p>
									<p class="comment">
										{{comment.message}}
									</p>
								</div>
							</div>
						</div>
					</div>
					{% empty %}
					<h3>No comments yet</h3>
					{% endfor %}
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action="{% url 'blog:blog_single_view' pid=single.id %}">
						{% csrf_token %}
						<input type="hidden" name="post" value={{single.id}}>
						{% if request.user.is_authenticated %}
							<input type="hidden" name="name" value={{request.user.username}}>
							<input type="hidden" name="email" value={{request.user.email}}>
						{% else %}
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>										
						</div>
						{% endif %}
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
						</div>
						<button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
					</form>
				</div>
			</div>
			
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% latest %}
					{% include 'blog/blog-single-tags.html' %}
					<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
					</div>
					{% category %}
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
										</div>
									</div>
									<input type="text" class="form-control" id="inlineFormInputGroup"
										placeholder="Enter email" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter email'">
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#">
        <h4>Alireza Rahimi</h4>
    </a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you
        should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
        andits detractors.
    </p>
</div>