blog/urls.py
from django.urls import path
from blog.views import *

from blog.rss import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_home_view, name='blog_home_view'),
    path('<int:pid>', blog_single_view, name='blog_single_view'),
    path('categor/<str:cat_name>', blog_home_view, name='category'),
    path('tag/<str:tag_name>', blog_home_view, name='tag'),
    path('author/<str:author_name>', blog_home_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', LatestEntriesFeed()),
    path('test', test, name='test')   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'
urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),
    path('email', email_view, name='email'),
    path('password', password_view, name='password')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class user_creation_form(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

users/views.py
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from users.forms import user_creation_form
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, HttpResponseRedirect


def login_view(request):                                              
    if not request.user.is_authenticated:
        if request.method == 'POST':
            entry_method = request.POST.get('entry_method')
            password = request.POST.get('password')
            if '@' in entry_method:
                try:
                    entry_method = User.objects.get(email=entry_method)
                    user = authenticate(request, username=entry_method.username, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect('/')
                except:
                    messages.add_message(request, messages.INFO, 'Incorrect username or password')
                    return render(request, 'users/login.html')
            else:
                user = authenticate(request, username=entry_method, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')
                else:
                    messages.add_message(request, messages.INFO, 'Incorrect username or password')
                    return render(request, 'users/login.html')
    return render(request, 'users/login.html')


def signup_view(request):
    if not request.user.is_authenticated:
        form = user_creation_form()
        if request.method == 'POST':
            form = user_creation_form(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('users:login'))
            else:
                messages.add_message(request, messages.ERROR, form.errors)
        context = {'form': form}
        return render(request, 'users/signup.html', context)
    else:
        return redirect('/')


@login_required()
def logout_view(request):
    logout(request)
    return redirect('/')


def password_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            entry_method = request.POST.get('entry_method')
            password = request.POST.get('old')
            new = request.POST.get('new')
            confirmation = request.POST.get('confirmation')
            if '@' in entry_method:
                if authenticate(request, username=entry_method.username, password=password):
                    user = User.objects.get(username=entry_method.username)
                    if new == confirmation:
                        user.password = make_password(new)
                        user.save()
                        return HttpResponseRedirect(reverse('users:login'))
                    else:
                        messages.add_message(request, messages.INFO, 'Passwords are not match')
                        return render(request, 'users/password.html')
                else:
                    messages.add_message(request, messages.INFO, 'User is not found')
                    return render(request, 'users/password.html')
            else:
                if authenticate(request, username=entry_method, password=password):
                    user = User.objects.get(username=entry_method)
                    if new == confirmation:
                        user.password = make_password(new)
                        user.save()
                        return HttpResponseRedirect(reverse('users:login'))
                    else:
                        messages.add_message(request, messages.INFO, 'Passwords are not match')
                        return render(request, 'users/password.html')
                else:
                    messages.add_message(request, messages.INFO, 'User is not found')
                    return render(request, 'users/password.html')
        else:
            return render(request, 'users/password.html')
    else:
        return redirect('/')


def email_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user=User.objects.filter(email=email)
        if user:
            user = User.objects.get(email=email)
            note = f'Hi dear {user.username} you asked for reset your passwrod\nTo continue the process please click the below link'
            message = EmailMessage(
                'request for password',
                f'{note}\nhttp://127.0.0.1:8000/users/password\nwebsite admin', 
                settings.EMAIL_HOST_USER,
                [email])
            message.fail_silently=False
            message.send()
            messages.add_message(request, messages.SUCCESS, 'Check your inbox or spam box')
        else:
            messages.add_message(request, messages.ERROR, 'Your email is not valid, Please Try again')
            return HttpResponseRedirect(reverse('users:email'))
    return render(request, 'users/email.html')

templates/users/email.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>send email</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <form method="post" action="{% url 'users:email' %}">
            {% csrf_token %}
            <input type="text" class="fadeIn second" name="email" placeholder="Email">
            <input type="submit" class="fadeIn fourth" value="Change">
        </form>
        {% include 'base-message.html' %}
        <script src="" async defer></script>
    </body>
</html>

templates/users/login.html
{% load static %}
<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
<link href="{% static 'css/login.css' %}" rel="stylesheet">
<!-- <script src="{% static 'js/bootstrap.min.js ' %}"></script> -->

<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
    <title>Login</title>
    <div id="formContent">
        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <input type="text" class="fadeIn second" name="entry_method" placeholder="Username or Email">
            <input type="password" class="fadeIn third" name="password" placeholder="Password">
            <input type="submit" class="fadeIn fourth" value="Log In">
        </form>
        {% include 'base-message.html' %}
        <div id="formFooter">
            <a class="underlineHover" href="{% url 'users:email' %}">Forgot Password?</a>
        </div>
    </div>
</div>

templates/users/password.html
{% load static %}
<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
<link href="{% static 'css/login.css' %}" rel="stylesheet">
<!-- <script src="{% static 'js/bootstrap.min.js ' %}"></script> -->

<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
    <title>Password</title>
    <div id="formContent">
        <form method="post" action="{% url 'users:password' %}">
            {% csrf_token %}
            <input type="text" class="fadeIn second" name="entry_method" placeholder="Username or Email">
            <input type="password" class="fadeIn third" name="old" placeholder="Old password">
            <input type="password" class="fadeIn second" name="new" placeholder="New password">
            <input type="password" class="fadeIn second" name="confirmation" placeholder="New password confirmation">
            <input type="submit" class="fadeIn fourth" value="Change">
        </form>
    </div>
    {% include 'base-message.html' %}
</div>

templates/users/signup.html
{% load static %}
<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
<link href="{% static 'css/login.css' %}" rel="stylesheet">
<!-- <script src="{% static 'js/bootstrap.min.js ' %}"></script> -->

<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
    <title>Signup</title>
    <div id="formContent">
        <!-- Tabs Titles -->

        <!-- Icon -->

        <!-- Login Form -->
        <form method="POST" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <input type="text" class="fadeIn second" name="username" placeholder="Username">
            <input name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required="" type="email">
            <input type="password" class="fadeIn third" name="password1" placeholder="Password">
            <input type="password" class="fadeIn third" name="password2" placeholder="confirmation">
            <input type="submit" class="fadeIn fourth" value="SignUp"> 
            {% include 'base-message.html'%}
        </form>
        

        <!-- Remind Passowrd -->
        <div id="formFooter">
            <a class="underlineHover" href="#">Forgot Password?</a>
        </div>

    </div>
</div>